<?php

namespace App\Models;

class Country {
  const country = 'country';
  const code = 'code';
  const name = 'name';

  public static function all() {
    return collect(self::$countries);
  }

  public static function findByCode(string $code) {
    return collect(self::$countries)->firstWhere(self::code, $code);
  }

  public static function findByName(string $name) {
    return collect(self::$countries)->firstWhere(self::name, $name);
  }

  protected static $countries = [
    [self::code => 'AFG', self::name => 'Afeganistão'],
    [self::code => 'ZAF', self::name => 'África do Sul'],
    [self::code => 'ALB', self::name => 'Albânia'],
    [self::code => 'DEU', self::name => 'Alemanha'],
    [self::code => 'AND', self::name => 'Andorra'],
    [self::code => 'AGO', self::name => 'Angola'],
    [self::code => 'AIA', self::name => 'Anguila'],
    [self::code => 'ATA', self::name => 'Antártica'],
    [self::code => 'ATG', self::name => 'Antígua e Barbuda'],
    [self::code => 'SAU', self::name => 'Arábia Saudita'],
    [self::code => 'DZA', self::name => 'Argélia'],
    [self::code => 'ARG', self::name => 'Argentina'],
    [self::code => 'ARM', self::name => 'Armênia'],
    [self::code => 'ABW', self::name => 'Aruba'],
    [self::code => 'AUS', self::name => 'Austrália'],
    [self::code => 'AUT', self::name => 'Áustria'],
    [self::code => 'AZE', self::name => 'Azerbaijão'],
    [self::code => 'BHS', self::name => 'Bahamas'],
    [self::code => 'BHR', self::name => 'Bahrein'],
    [self::code => 'BGD', self::name => 'Bangladesh'],
    [self::code => 'BRB', self::name => 'Barbados'],
    [self::code => 'BLR', self::name => 'Belarus'],
    [self::code => 'BEL', self::name => 'Bélgica'],
    [self::code => 'BLZ', self::name => 'Belize'],
    [self::code => 'BEN', self::name => 'Benin'],
    [self::code => 'BMU', self::name => 'Bermudas'],
    [self::code => 'BOL', self::name => 'Bolívia'],
    [self::code => 'BIH', self::name => 'Bósnia e Herzegovina'],
    [self::code => 'BWA', self::name => 'Botsuana'],
    [self::code => 'BRA', self::name => 'Brasil'],
    [self::code => 'BRN', self::name => 'Brunei'],
    [self::code => 'BGR', self::name => 'Bulgária'],
    [self::code => 'BFA', self::name => 'Burkina Faso'],
    [self::code => 'BDI', self::name => 'Burundi'],
    [self::code => 'BTN', self::name => 'Butão'],
    [self::code => 'CPV', self::name => 'Cabo Verde'],
    [self::code => 'CMR', self::name => 'Camarões'],
    [self::code => 'KHM', self::name => 'Camboja'],
    [self::code => 'CAN', self::name => 'Canadá'],
    [self::code => 'KAZ', self::name => 'Cazaquistão'],
    [self::code => 'TCD', self::name => 'Chade'],
    [self::code => 'CHL', self::name => 'Chile'],
    [self::code => 'CHN', self::name => 'China'],
    [self::code => 'CYP', self::name => 'Chipre'],
    [self::code => 'VAT', self::name => 'Cidade do Vaticano'],
    [self::code => 'SGP', self::name => 'Cingapura'],
    [self::code => 'COL', self::name => 'Colômbia'],
    [self::code => 'COM', self::name => 'Comores'],
    [self::code => 'PRK', self::name => 'Coréia do Norte'],
    [self::code => 'KOR', self::name => 'Coréia do Sul'],
    [self::code => 'CIV', self::name => 'Costa do Marfim'],
    [self::code => 'CRI', self::name => 'Costa Rica'],
    [self::code => 'HRV', self::name => 'Croácia'],
    [self::code => 'CUB', self::name => 'Cuba'],
    [self::code => 'CUW', self::name => 'Curaçao'],
    [self::code => 'DNK', self::name => 'Dinamarca'],
    [self::code => 'DJI', self::name => 'Djibouti'],
    [self::code => 'DMA', self::name => 'Dominica'],
    [self::code => 'EGY', self::name => 'Egito'],
    [self::code => 'SLV', self::name => 'El Salvador'],
    [self::code => 'ARE', self::name => 'Emirados Árabes Unidos'],
    [self::code => 'ECU', self::name => 'Equador'],
    [self::code => 'ERI', self::name => 'Eritreia'],
    [self::code => 'SVK', self::name => 'Eslováquia'],
    [self::code => 'SVN', self::name => 'Eslovênia'],
    [self::code => 'ESP', self::name => 'Espanha'],
    [self::code => 'FSM', self::name => 'Estados Federados da Micronésia'],
    [self::code => 'USA', self::name => 'Estados Unidos da América'],
    [self::code => 'EST', self::name => 'Estônia'],
    [self::code => 'SWZ', self::name => 'Eswatini'],
    [self::code => 'ETH', self::name => 'Etiópia'],
    [self::code => 'FJI', self::name => 'Fiji'],
    [self::code => 'PHL', self::name => 'Filipinas'],
    [self::code => 'FIN', self::name => 'Finlândia'],
    [self::code => 'FRA', self::name => 'França'],
    [self::code => 'GAB', self::name => 'Gabão'],
    [self::code => 'GMB', self::name => 'Gâmbia'],
    [self::code => 'GHA', self::name => 'Gana'],
    [self::code => 'GEO', self::name => 'Geórgia'],
    [self::code => 'SGS', self::name => 'Geórgia do Sul e as Ilhas Sandwich do Sul'],
    [self::code => 'GIB', self::name => 'Gibraltar'],
    [self::code => 'GRC', self::name => 'Grécia'],
    [self::code => 'GRD', self::name => 'Grenada'],
    [self::code => 'GRL', self::name => 'Groenlândia'],
    [self::code => 'GLP', self::name => 'Guadalupe'],
    [self::code => 'GUM', self::name => 'Guam'],
    [self::code => 'GTM', self::name => 'Guatemala'],
    [self::code => 'GGY', self::name => 'Guernsey'],
    [self::code => 'GUY', self::name => 'Guiana'],
    [self::code => 'GUF', self::name => 'Guiana Francesa'],
    [self::code => 'GIN', self::name => 'Guiné'],
    [self::code => 'GNQ', self::name => 'Guiné Equatorial'],
    [self::code => 'GNB', self::name => 'Guiné-Bissau'],
    [self::code => 'HTI', self::name => 'Haiti'],
    [self::code => 'HND', self::name => 'Honduras'],
    [self::code => 'HKG', self::name => 'Hong Kong'],
    [self::code => 'HUN', self::name => 'Hungria'],
    [self::code => 'YEM', self::name => 'Iêmen'],
    [self::code => 'BVT', self::name => 'Ilha Bouvet'],
    [self::code => 'REU', self::name => 'Ilha da Reunião'],
    [self::code => 'IMN', self::name => 'Ilha de Man'],
    [self::code => 'CXR', self::name => 'Ilha de Natal'],
    [self::code => 'NFK', self::name => 'Ilha Norfolk'],
    [self::code => 'ALA', self::name => 'Ilhas Åland'],
    [self::code => 'CYM', self::name => 'Ilhas Cayman'],
    [self::code => 'CCK', self::name => 'Ilhas Cocos'],
    [self::code => 'COK', self::name => 'Ilhas Cook'],
    [self::code => 'FRO', self::name => 'Ilhas Faroe'],
    [self::code => 'FLK', self::name => 'Ilhas Malvinas'],
    [self::code => 'MNP', self::name => 'Ilhas Marianas do Norte'],
    [self::code => 'MHL', self::name => 'Ilhas Marshall'],
    [self::code => 'UMI', self::name => 'Ilhas Menores Distantes dos Estados Unidos'],
    [self::code => 'PCN', self::name => 'Ilhas Pitcairn'],
    [self::code => 'SLB', self::name => 'Ilhas Salomão'],
    [self::code => 'TCA', self::name => 'Ilhas Turcas e Caicos'],
    [self::code => 'VGB', self::name => 'Ilhas Virgens (Reino Unido)'],
    [self::code => 'VIR', self::name => 'Ilhas Virgens dos Estados Unidos'],
    [self::code => 'IND', self::name => 'Índia'],
    [self::code => 'IDN', self::name => 'Indonésia'],
    [self::code => 'IRN', self::name => 'Irã'],
    [self::code => 'IRQ', self::name => 'Iraque'],
    [self::code => 'IRL', self::name => 'Irlanda'],
    [self::code => 'ISL', self::name => 'Islândia'],
    [self::code => 'ISR', self::name => 'Israel'],
    [self::code => 'ITA', self::name => 'Itália'],
    [self::code => 'JAM', self::name => 'Jamaica'],
    [self::code => 'JPN', self::name => 'Japão'],
    [self::code => 'JEY', self::name => 'Jersey'],
    [self::code => 'JOR', self::name => 'Jordânia'],
    [self::code => 'KIR', self::name => 'Kiribati'],
    [self::code => 'XXK', self::name => 'Kosovo'],
    [self::code => 'KWT', self::name => 'Kuwait'],
    [self::code => 'LAO', self::name => 'Laos'],
    [self::code => 'LSO', self::name => 'Lesotho'],
    [self::code => 'LVA', self::name => 'Letônia'],
    [self::code => 'LBN', self::name => 'Líbano'],
    [self::code => 'LBR', self::name => 'Libéria'],
    [self::code => 'LBY', self::name => 'Líbia'],
    [self::code => 'LIE', self::name => 'Liechtenstein'],
    [self::code => 'LTU', self::name => 'Lituânia'],
    [self::code => 'LUX', self::name => 'Luxemburgo'],
    [self::code => 'MAC', self::name => 'Macau'],
    [self::code => 'MDG', self::name => 'Madagascar'],
    [self::code => 'MYS', self::name => 'Malásia'],
    [self::code => 'MWI', self::name => 'Malauí'],
    [self::code => 'MDV', self::name => 'Maldivas'],
    [self::code => 'MLI', self::name => 'Mali'],
    [self::code => 'MLT', self::name => 'Malta'],
    [self::code => 'MAR', self::name => 'Marrocos'],
    [self::code => 'MTQ', self::name => 'Martinica'],
    [self::code => 'MUS', self::name => 'Maurício'],
    [self::code => 'MRT', self::name => 'Mauritânia'],
    [self::code => 'MYT', self::name => 'Mayotte'],
    [self::code => 'MEX', self::name => 'México'],
    [self::code => 'MMR', self::name => 'Mianmar'],
    [self::code => 'MOZ', self::name => 'Moçambique'],
    [self::code => 'MDA', self::name => 'Moldávia'],
    [self::code => 'MNG', self::name => 'Mongólia'],
    [self::code => 'MNE', self::name => 'Montenegro'],
    [self::code => 'MSR', self::name => 'Montserrat'],
    [self::code => 'NAM', self::name => 'Namíbia'],
    [self::code => 'NRU', self::name => 'Nauru'],
    [self::code => 'NPL', self::name => 'Nepal'],
    [self::code => 'NIC', self::name => 'Nicarágua'],
    [self::code => 'NER', self::name => 'Níger'],
    [self::code => 'NGA', self::name => 'Nigéria'],
    [self::code => 'NIU', self::name => 'Niue'],
    [self::code => 'MKD', self::name => 'Norte da Macedônia'],
    [self::code => 'NOR', self::name => 'Noruega'],
    [self::code => 'NCL', self::name => 'Nova Caledônia'],
    [self::code => 'NZL', self::name => 'Nova Zelândia'],
    [self::code => 'OMN', self::name => 'Omã'],
    [self::code => 'HMD', self::name => 'Ouvido e Ilhas McDonald'],
    [self::code => 'NLD', self::name => 'Países Baixos'],
    [self::code => 'BES', self::name => 'Países Baixos Caribenhos'],
    [self::code => 'PLW', self::name => 'Palau'],
    [self::code => 'PSE', self::name => 'Palestina'],
    [self::code => 'PAN', self::name => 'Panamá'],
    [self::code => 'PNG', self::name => 'Papua Nova Guiné'],
    [self::code => 'PAK', self::name => 'Paquistão'],
    [self::code => 'PRY', self::name => 'Paraguai'],
    [self::code => 'PER', self::name => 'Peru'],
    [self::code => 'PYF', self::name => 'Polinésia Francesa'],
    [self::code => 'POL', self::name => 'Polônia'],
    [self::code => 'PRI', self::name => 'Porto Rico'],
    [self::code => 'PRT', self::name => 'Portugal'],
    [self::code => 'MCO', self::name => 'Principado de Mônaco'],
    [self::code => 'QAT', self::name => 'Qatar'],
    [self::code => 'KEN', self::name => 'Quênia'],
    [self::code => 'KGZ', self::name => 'Quirguizistão'],
    [self::code => 'GBR', self::name => 'Reino Unido'],
    [self::code => 'CAF', self::name => 'República Centro-Africana'],
    [self::code => 'COD', self::name => 'República Democrática do Congo'],
    [self::code => 'COG', self::name => 'República do Congo'],
    [self::code => 'DOM', self::name => 'República Dominicana'],
    [self::code => 'ROU', self::name => 'Romênia'],
    [self::code => 'RWA', self::name => 'Ruanda'],
    [self::code => 'RUS', self::name => 'Rússia'],
    [self::code => 'ESH', self::name => 'Saara Ocidental'],
    [self::code => 'WSM', self::name => 'Samoa'],
    [self::code => 'ASM', self::name => 'Samoa Americana'],
    [self::code => 'SHN', self::name => 'Santa Helena, Ascensão e Tristão da Cunha'],
    [self::code => 'LCA', self::name => 'Santa Lúcia'],
    [self::code => 'BLM', self::name => 'Santo Bartolomeu'],
    [self::code => 'SMR', self::name => 'São Marino'],
    [self::code => 'MAF', self::name => 'São Martinho'],
    [self::code => 'SPM', self::name => 'São Pedro e Miquelon'],
    [self::code => 'STP', self::name => 'São Tomé e Príncipe'],
    [self::code => 'VCT', self::name => 'São Vicente e as Granadinas'],
    [self::code => 'SEN', self::name => 'Senegal'],
    [self::code => 'SLE', self::name => 'Serra Leoa'],
    [self::code => 'SRB', self::name => 'Sérvia'],
    [self::code => 'SYC', self::name => 'Seychelles'],
    [self::code => 'SXM', self::name => 'Sint Maarten'],
    [self::code => 'SYR', self::name => 'Síria'],
    [self::code => 'SOM', self::name => 'Somália'],
    [self::code => 'LKA', self::name => 'Sri Lanka'],
    [self::code => 'KNA', self::name => 'St. Kitts e Nevis'],
    [self::code => 'SDN', self::name => 'Sudão'],
    [self::code => 'SSD', self::name => 'Sudão do Sul'],
    [self::code => 'SWE', self::name => 'Suécia'],
    [self::code => 'CHE', self::name => 'Suíça'],
    [self::code => 'SUR', self::name => 'Suriname'],
    [self::code => 'SJM', self::name => 'Svalbard e Jan Mayen'],
    [self::code => 'THA', self::name => 'Tailândia'],
    [self::code => 'TWN', self::name => 'Taiwan'],
    [self::code => 'TJK', self::name => 'Tajiquistão'],
    [self::code => 'TZA', self::name => 'Tanzânia'],
    [self::code => 'CZE', self::name => 'Tcheca'],
    [self::code => 'IOT', self::name => 'Território Britânico do Oceano Índico'],
    [self::code => 'ATF', self::name => 'Territórios Franceses do Sul e Antártico'],
    [self::code => 'TLS', self::name => 'Timor Leste'],
    [self::code => 'TGO', self::name => 'Togo'],
    [self::code => 'TKL', self::name => 'Tokelau'],
    [self::code => 'TON', self::name => 'Tonga'],
    [self::code => 'TTO', self::name => 'Trinidad e Tobago'],
    [self::code => 'TUN', self::name => 'Tunísia'],
    [self::code => 'TKM', self::name => 'Turcomenistão'],
    [self::code => 'TUR', self::name => 'Turquia'],
    [self::code => 'TUV', self::name => 'Tuvalu'],
    [self::code => 'UKR', self::name => 'Ucrânia'],
    [self::code => 'UGA', self::name => 'Uganda'],
    [self::code => 'URY', self::name => 'Uruguai'],
    [self::code => 'UZB', self::name => 'Uzbequistão'],
    [self::code => 'VUT', self::name => 'Vanuatu'],
    [self::code => 'VEN', self::name => 'Venezuela'],
    [self::code => 'VNM', self::name => 'Vietnã'],
    [self::code => 'WLF', self::name => 'Wallis e Futuna'],
    [self::code => 'ZMB', self::name => 'Zâmbia'],
    [self::code => 'ZWE', self::name => 'Zimbábue']
  ];
}